### ISSUE TITLE
Webinterface just loading

### ISSUE THREAD

**Issue by timvgl** [MathieuMoalic/amumax#69]
Hi,
I have just downloaded amumax and installed it. The script that I have created seems to be running fine (checking via the console). However unfortunately I cannot access the webinterface. The loading symbol does not vanish and just keeps running.
Any idea?
All the best,
Tim

**Comment by timvgl** [comment]
Hi,
okay so with the newer version I am able to enter the UI but it is not having a connection. Even not after 30s.
![image](https://github.com/user-attachments/assets/775bc39c-0ac8-499c-9ae2-fda4f57c1928)
![image](https://github.com/user-attachments/assets/c65abcd0-2a7a-4a81-a7fb-b89ef3ff6b8d)
Debugging mode gives:
![image](https://github.com/user-attachments/assets/a7b584b3-7897-40c7-a7fc-0d43e5317c2b)
Thanks a lot!

**Comment by MathieuMoalic** [comment]
I really appreaciate the feedback! 
So there is definitely a problem with the websocket connection. And I think I have a good idea about what is wrong. Namely this line: 
https://github.com/MathieuMoalic/amumax/blob/aba3e640c4528871ba31d481ba49f11a59568b3a/frontend/src/api/websocket.ts#L17

Which defines the websocket url, I thought it would just be "/ws" on the built binaries but I guess I was wrong. The bug is fixed, I will upload a new release in a few minutes. I will will named "2024.10.23" like the current release, I will replace it.
Please re-open the issue if it's not fixed!
